import { Tablero } from "./tablero.js";
import { Cell } from "./celula.js";
const tablero = new Tablero();
tablero.giveCellPosition();
tablero.traversTable();
// celula.giveCellPosition(tablero);
// console.log(tablero[2][3]);
// let n = Celula.numberofNeightbours(tablero[2][3], tablero);
// console.log(n);
// console.log(Celula.isCellAlive(tablero[2][3], n));
// console.log(tablero[2][3]);
